import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Almarai, Noto_Serif_Display } from "next/font/google"; // 👈 import fonts
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const almarai = Almarai({
  weight: "400", // 👈 regular
  variable: "--font-almarai",
  subsets: ["latin"],
  display: "swap",
});

const notoSerifDisplay = Noto_Serif_Display({
  subsets: ["latin"],
  variable: "--font-noto-serif-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${almarai.variable} 
          ${notoSerifDisplay.variable}
          ${geistSans.variable} 
          ${geistMono.variable} 
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
